-- 코드를 입력하세요
SELECT a.FOOD_TYPE, a.REST_ID, a.REST_NAME, a.FAVORITES
FROM REST_INFO a
WHERE (a.FOOD_TYPE, a.FAVORITES) IN (
    SELECT b.FOOD_TYPE, MAX(b.FAVORITES)
    FROM REST_INFO b
    GROUP BY FOOD_TYPE)
ORDER BY a.FOOD_TYPE DESC;
