SELECT
    c.CAR_ID,
    CASE
        WHEN EXISTS (
            SELECT r.CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY r
            WHERE r.CAR_ID = c.CAR_ID
              AND '2022-10-16' BETWEEN r.START_DATE AND r.END_DATE
        )
        THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
GROUP BY c.CAR_ID
ORDER BY c.CAR_ID DESC;
