-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', f.BOARD_ID, '/', f.FILE_ID, f.FILE_NAME, f.FILE_EXT) AS FILSE_PATH
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_FILE f
    ON f.BOARD_ID = b.BOARD_ID
WHERE b.VIEWS IN (SELECT MAX(c.VIEWS)
                 FROM USED_GOODS_BOARD c)
ORDER BY f.FILE_ID DESC;
